use_frameworks!
platform :ios, '10.0'

target 'weather' do
  
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  
  target 'weatherTests' do
    inherit! :search_paths

    pod 'Alamofire', '4.8.2'
    
  end
end

