use_frameworks!
platform :ios, '10.0'

target 'weather' do
  
  pod 'Alamofire', '4.8.2'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SDWebImage', '~>3.7'
  
  target 'weatherTests' do
    inherit! :search_paths

    pod 'Alamofire', '4.8.2'
    
  end
end

