name: Swift

on:
  pull_request:
    branches: [ ci ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1.57.0
      with:
          ruby-version: 2.4.0
          bundler-cache: true
    - name: Run pod
      run: cd weather && pod install
    - name: Test - Fastlane tests
      run: bundle exec fastlane test
